# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('class_code', models.IntegerField(unique=True)),
                ('classspec_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('occupational_category', models.CharField(max_length=200)),
                ('skills', models.TextField()),
                ('related_keywords', models.TextField()),
                ('salary_low', models.IntegerField(default=0)),
                ('salary_high', models.IntegerField(default=0)),
                ('external_url', models.URLField()),
                ('career_ladder_url', models.URLField()),
                ('description', models.TextField()),
                ('qualifications', models.TextField()),
                ('responsibilities', models.TextField()),
                ('exam_notes', models.TextField()),
                ('categories', models.ManyToManyField(to='jobs.Category')),
            ],
        ),
    ]
