# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='jobclass',
            options={'verbose_name_plural': 'Job Classes'},
        ),
        migrations.AlterField(
            model_name='jobclass',
            name='related_keywords',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobclass',
            name='skills',
            field=models.CharField(max_length=200),
        ),
    ]
