# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20170829_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobclass',
            name='alias',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
