# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobclass_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('class_code', models.IntegerField(unique=True)),
                ('open_date', models.DateField(null=True)),
                ('exam_date', models.DateField(null=True)),
            ],
        ),
    ]
